# Generated by Django 3.1.4 on 2021-01-23 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210123_0737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='user',
        ),
        migrations.AddField(
            model_name='supplier',
            name='address',
            field=models.CharField(default='Dhaka, BD', max_length=500),
        ),
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='name',
            field=models.CharField(default='Digiden', max_length=200),
        ),
        migrations.AddField(
            model_name='supplier',
            name='phone',
            field=models.CharField(default='01800000000', max_length=25, unique=True),
            preserve_default=False,
        ),
    ]
