# Generated by Django 3.1.4 on 2021-01-23 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210123_0839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderunit',
            name='order',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productunit',
            name='price_sold',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productunit',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('product_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.productmodel')),
            ],
        ),
        migrations.AddField(
            model_name='orderunit',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='main.orderitem'),
            preserve_default=False,
        ),
    ]
