# Generated by Django 3.1.4 on 2021-01-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210123_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productunit',
            name='price_sold',
            field=models.DecimalField(decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='profit',
            field=models.DecimalField(decimal_places=2, max_digits=18, null=True),
        ),
    ]
