# Generated by Django 3.1.4 on 2021-01-30 13:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210130_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='productunit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productunit',
            name='sold_at',
            field=models.DateTimeField(null=True),
        ),
    ]
