# Generated by Django 3.1.4 on 2021-02-02 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210130_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productunit',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='main.investor'),
        ),
    ]
