# Generated by Django 3.1.4 on 2021-02-02 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210203_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productunit',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='main.store'),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='main.supplier'),
        ),
    ]
